# Generated by Django 2.1.3 on 2018-11-10 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20181110_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='time',
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
